/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers';
import type { FunctionFragment, Result } from '@ethersproject/abi';
import type { Listener, Provider } from '@ethersproject/providers';
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from '../common';

export interface BrainFuckVMInterface extends utils.Interface {
  functions: {
    'runBrainFuckCode(bytes,bytes)': FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: 'runBrainFuckCode'): FunctionFragment;

  encodeFunctionData(
    functionFragment: 'runBrainFuckCode',
    values: [BytesLike, BytesLike],
  ): string;

  decodeFunctionResult(
    functionFragment: 'runBrainFuckCode',
    data: BytesLike,
  ): Result;

  events: {};
}

export interface BrainFuckVM extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: BrainFuckVMInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>,
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>,
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    runBrainFuckCode(
      code: BytesLike,
      input: BytesLike,
      overrides?: CallOverrides,
    ): Promise<[string] & { out: string }>;
  };

  runBrainFuckCode(
    code: BytesLike,
    input: BytesLike,
    overrides?: CallOverrides,
  ): Promise<string>;

  callStatic: {
    runBrainFuckCode(
      code: BytesLike,
      input: BytesLike,
      overrides?: CallOverrides,
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    runBrainFuckCode(
      code: BytesLike,
      input: BytesLike,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    runBrainFuckCode(
      code: BytesLike,
      input: BytesLike,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;
  };
}
