"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.KeyDataStorage__factory = exports.IndexedDataStorage__factory = exports.EfficientChunkedDataStorage__factory = exports.ChunkedDataStorage__factory = exports.AdminEditableStorage__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var AdminEditableStorage__factory_1 = require("./AdminEditableStorage__factory");
Object.defineProperty(exports, "AdminEditableStorage__factory", { enumerable: true, get: function () { return AdminEditableStorage__factory_1.AdminEditableStorage__factory; } });
var ChunkedDataStorage__factory_1 = require("./ChunkedDataStorage__factory");
Object.defineProperty(exports, "ChunkedDataStorage__factory", { enumerable: true, get: function () { return ChunkedDataStorage__factory_1.ChunkedDataStorage__factory; } });
var EfficientChunkedDataStorage__factory_1 = require("./EfficientChunkedDataStorage__factory");
Object.defineProperty(exports, "EfficientChunkedDataStorage__factory", { enumerable: true, get: function () { return EfficientChunkedDataStorage__factory_1.EfficientChunkedDataStorage__factory; } });
var IndexedDataStorage__factory_1 = require("./IndexedDataStorage__factory");
Object.defineProperty(exports, "IndexedDataStorage__factory", { enumerable: true, get: function () { return IndexedDataStorage__factory_1.IndexedDataStorage__factory; } });
var KeyDataStorage__factory_1 = require("./KeyDataStorage__factory");
Object.defineProperty(exports, "KeyDataStorage__factory", { enumerable: true, get: function () { return KeyDataStorage__factory_1.KeyDataStorage__factory; } });
//# sourceMappingURL=index.js.map