"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IERC2981__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var IERC2981__factory_1 = require("./IERC2981__factory");
Object.defineProperty(exports, "IERC2981__factory", { enumerable: true, get: function () { return IERC2981__factory_1.IERC2981__factory; } });
//# sourceMappingURL=index.js.map