"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IRenderer__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var IRenderer__factory_1 = require("./IRenderer__factory");
Object.defineProperty(exports, "IRenderer__factory", { enumerable: true, get: function () { return IRenderer__factory_1.IRenderer__factory; } });
//# sourceMappingURL=index.js.map