"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IVirtualMachine__factory = exports.IRenderer__factory = exports.IDataStorage__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var IDataStorage__factory_1 = require("./IDataStorage__factory");
Object.defineProperty(exports, "IDataStorage__factory", { enumerable: true, get: function () { return IDataStorage__factory_1.IDataStorage__factory; } });
var IRenderer__factory_1 = require("./IRenderer__factory");
Object.defineProperty(exports, "IRenderer__factory", { enumerable: true, get: function () { return IRenderer__factory_1.IRenderer__factory; } });
var IVirtualMachine__factory_1 = require("./IVirtualMachine__factory");
Object.defineProperty(exports, "IVirtualMachine__factory", { enumerable: true, get: function () { return IVirtualMachine__factory_1.IVirtualMachine__factory; } });
//# sourceMappingURL=index.js.map