/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AdminEditableStorage__factory } from './AdminEditableStorage__factory';
export { ChunkedDataStorage__factory } from './ChunkedDataStorage__factory';
export { EfficientChunkedDataStorage__factory } from './EfficientChunkedDataStorage__factory';
export { IndexedDataStorage__factory } from './IndexedDataStorage__factory';
export { KeyDataStorage__factory } from './KeyDataStorage__factory';
