"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.RendererRegistry__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var RendererRegistry__factory_1 = require("./RendererRegistry__factory");
Object.defineProperty(exports, "RendererRegistry__factory", { enumerable: true, get: function () { return RendererRegistry__factory_1.RendererRegistry__factory; } });
//# sourceMappingURL=index.js.map