"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MiddlewareRenderer__factory = exports.CompactMiddlewareRenderer__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var CompactMiddlewareRenderer__factory_1 = require("./CompactMiddlewareRenderer__factory");
Object.defineProperty(exports, "CompactMiddlewareRenderer__factory", { enumerable: true, get: function () { return CompactMiddlewareRenderer__factory_1.CompactMiddlewareRenderer__factory; } });
var MiddlewareRenderer__factory_1 = require("./MiddlewareRenderer__factory");
Object.defineProperty(exports, "MiddlewareRenderer__factory", { enumerable: true, get: function () { return MiddlewareRenderer__factory_1.MiddlewareRenderer__factory; } });
//# sourceMappingURL=index.js.map