"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CompressedAnimatedGifRenderer__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var CompressedAnimatedGifRenderer__factory_1 = require("./CompressedAnimatedGifRenderer__factory");
Object.defineProperty(exports, "CompressedAnimatedGifRenderer__factory", { enumerable: true, get: function () { return CompressedAnimatedGifRenderer__factory_1.CompressedAnimatedGifRenderer__factory; } });
//# sourceMappingURL=index.js.map