"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ERC721APausable__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var ERC721APausable__factory_1 = require("./ERC721APausable__factory");
Object.defineProperty(exports, "ERC721APausable__factory", { enumerable: true, get: function () { return ERC721APausable__factory_1.ERC721APausable__factory; } });
//# sourceMappingURL=index.js.map