"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.PixelGrid8Renderer__factory = exports.PixelGrid24Renderer__factory = exports.PixelGrid16Renderer__factory = exports.PathRenderer__factory = exports.MonoPixelGrid8Renderer__factory = exports.MonoPixelGrid24Renderer__factory = exports.MonoPixelGrid16Renderer__factory = exports.LayerCompositeRenderer__factory = exports.IdentityRenderer__factory = exports.HSLPixelGrid8Renderer__factory = exports.HSLPixelGrid24Renderer__factory = exports.HSLPixelGrid16Renderer__factory = exports.GifImageRenderer__factory = exports.DotMatrixRenderer__factory = exports.CompressedAnimatedGifRenderer__factory = exports.CompactMiddlewareRenderer__factory = exports.BackgroundSvgRenderer__factory = exports.AnimatedGifImageRenderer__factory = exports.AlphaFilterRenderer__factory = exports.configuredGifImageRendererSol = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.configuredGifImageRendererSol = __importStar(require("./ConfiguredGifImageRenderer.sol"));
var AlphaFilterRenderer__factory_1 = require("./AlphaFilterRenderer__factory");
Object.defineProperty(exports, "AlphaFilterRenderer__factory", { enumerable: true, get: function () { return AlphaFilterRenderer__factory_1.AlphaFilterRenderer__factory; } });
var AnimatedGifImageRenderer__factory_1 = require("./AnimatedGifImageRenderer__factory");
Object.defineProperty(exports, "AnimatedGifImageRenderer__factory", { enumerable: true, get: function () { return AnimatedGifImageRenderer__factory_1.AnimatedGifImageRenderer__factory; } });
var BackgroundSvgRenderer__factory_1 = require("./BackgroundSvgRenderer__factory");
Object.defineProperty(exports, "BackgroundSvgRenderer__factory", { enumerable: true, get: function () { return BackgroundSvgRenderer__factory_1.BackgroundSvgRenderer__factory; } });
var CompactMiddlewareRenderer__factory_1 = require("./CompactMiddlewareRenderer__factory");
Object.defineProperty(exports, "CompactMiddlewareRenderer__factory", { enumerable: true, get: function () { return CompactMiddlewareRenderer__factory_1.CompactMiddlewareRenderer__factory; } });
var CompressedAnimatedGifRenderer__factory_1 = require("./CompressedAnimatedGifRenderer__factory");
Object.defineProperty(exports, "CompressedAnimatedGifRenderer__factory", { enumerable: true, get: function () { return CompressedAnimatedGifRenderer__factory_1.CompressedAnimatedGifRenderer__factory; } });
var DotMatrixRenderer__factory_1 = require("./DotMatrixRenderer__factory");
Object.defineProperty(exports, "DotMatrixRenderer__factory", { enumerable: true, get: function () { return DotMatrixRenderer__factory_1.DotMatrixRenderer__factory; } });
var GifImageRenderer__factory_1 = require("./GifImageRenderer__factory");
Object.defineProperty(exports, "GifImageRenderer__factory", { enumerable: true, get: function () { return GifImageRenderer__factory_1.GifImageRenderer__factory; } });
var HSLPixelGrid16Renderer__factory_1 = require("./HSLPixelGrid16Renderer__factory");
Object.defineProperty(exports, "HSLPixelGrid16Renderer__factory", { enumerable: true, get: function () { return HSLPixelGrid16Renderer__factory_1.HSLPixelGrid16Renderer__factory; } });
var HSLPixelGrid24Renderer__factory_1 = require("./HSLPixelGrid24Renderer__factory");
Object.defineProperty(exports, "HSLPixelGrid24Renderer__factory", { enumerable: true, get: function () { return HSLPixelGrid24Renderer__factory_1.HSLPixelGrid24Renderer__factory; } });
var HSLPixelGrid8Renderer__factory_1 = require("./HSLPixelGrid8Renderer__factory");
Object.defineProperty(exports, "HSLPixelGrid8Renderer__factory", { enumerable: true, get: function () { return HSLPixelGrid8Renderer__factory_1.HSLPixelGrid8Renderer__factory; } });
var IdentityRenderer__factory_1 = require("./IdentityRenderer__factory");
Object.defineProperty(exports, "IdentityRenderer__factory", { enumerable: true, get: function () { return IdentityRenderer__factory_1.IdentityRenderer__factory; } });
var LayerCompositeRenderer__factory_1 = require("./LayerCompositeRenderer__factory");
Object.defineProperty(exports, "LayerCompositeRenderer__factory", { enumerable: true, get: function () { return LayerCompositeRenderer__factory_1.LayerCompositeRenderer__factory; } });
var MonoPixelGrid16Renderer__factory_1 = require("./MonoPixelGrid16Renderer__factory");
Object.defineProperty(exports, "MonoPixelGrid16Renderer__factory", { enumerable: true, get: function () { return MonoPixelGrid16Renderer__factory_1.MonoPixelGrid16Renderer__factory; } });
var MonoPixelGrid24Renderer__factory_1 = require("./MonoPixelGrid24Renderer__factory");
Object.defineProperty(exports, "MonoPixelGrid24Renderer__factory", { enumerable: true, get: function () { return MonoPixelGrid24Renderer__factory_1.MonoPixelGrid24Renderer__factory; } });
var MonoPixelGrid8Renderer__factory_1 = require("./MonoPixelGrid8Renderer__factory");
Object.defineProperty(exports, "MonoPixelGrid8Renderer__factory", { enumerable: true, get: function () { return MonoPixelGrid8Renderer__factory_1.MonoPixelGrid8Renderer__factory; } });
var PathRenderer__factory_1 = require("./PathRenderer__factory");
Object.defineProperty(exports, "PathRenderer__factory", { enumerable: true, get: function () { return PathRenderer__factory_1.PathRenderer__factory; } });
var PixelGrid16Renderer__factory_1 = require("./PixelGrid16Renderer__factory");
Object.defineProperty(exports, "PixelGrid16Renderer__factory", { enumerable: true, get: function () { return PixelGrid16Renderer__factory_1.PixelGrid16Renderer__factory; } });
var PixelGrid24Renderer__factory_1 = require("./PixelGrid24Renderer__factory");
Object.defineProperty(exports, "PixelGrid24Renderer__factory", { enumerable: true, get: function () { return PixelGrid24Renderer__factory_1.PixelGrid24Renderer__factory; } });
var PixelGrid8Renderer__factory_1 = require("./PixelGrid8Renderer__factory");
Object.defineProperty(exports, "PixelGrid8Renderer__factory", { enumerable: true, get: function () { return PixelGrid8Renderer__factory_1.PixelGrid8Renderer__factory; } });
//# sourceMappingURL=index.js.map