"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LayerCompositeRenderer__factory = exports.ImageBasedLayerCompositeRenderer__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var ImageBasedLayerCompositeRenderer__factory_1 = require("./ImageBasedLayerCompositeRenderer__factory");
Object.defineProperty(exports, "ImageBasedLayerCompositeRenderer__factory", { enumerable: true, get: function () { return ImageBasedLayerCompositeRenderer__factory_1.ImageBasedLayerCompositeRenderer__factory; } });
var LayerCompositeRenderer__factory_1 = require("./LayerCompositeRenderer__factory");
Object.defineProperty(exports, "LayerCompositeRenderer__factory", { enumerable: true, get: function () { return LayerCompositeRenderer__factory_1.LayerCompositeRenderer__factory; } });
//# sourceMappingURL=index.js.map