/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IRenderer } from './IRenderer';
export type { IRendererPayable } from './IRendererPayable';
export type { ISplitMain } from './ISplitMain';
export type { IVirtualMachine } from './IVirtualMachine';
