/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BrainFuckFactory } from './BrainFuckFactory';
export type { BrainFuckStore } from './BrainFuckStore';
