/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IDataStorage__factory } from './IDataStorage__factory';
export { IRenderer__factory } from './IRenderer__factory';
export { IVirtualMachine__factory } from './IVirtualMachine__factory';
