/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AdminEditableStorage } from './AdminEditableStorage';
export type { ChunkedDataStorage } from './ChunkedDataStorage';
export type { EfficientChunkedDataStorage } from './EfficientChunkedDataStorage';
export type { IndexedDataStorage } from './IndexedDataStorage';
export type { KeyDataStorage } from './KeyDataStorage';
