/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { FunctionFragment, Result } from '@ethersproject/abi';
import type { Listener, Provider } from '@ethersproject/providers';
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers';
import type {
  OnEvent,
  TypedEvent,
  TypedEventFilter,
  TypedListener,
} from '../../common';

export interface DotMatrixRendererInterface extends utils.Interface {
  functions: {
    'RADIUS_MAX()': FunctionFragment;
    'RADIUS_MIN()': FunctionFragment;
    'additionalMetadataURI()': FunctionFragment;
    'attributes(bytes)': FunctionFragment;
    'outSize()': FunctionFragment;
    'owner()': FunctionFragment;
    'render(bytes)': FunctionFragment;
    'renderAttributeKey()': FunctionFragment;
    'renderRaw(bytes)': FunctionFragment;
    'supportsInterface(bytes4)': FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | 'RADIUS_MAX'
      | 'RADIUS_MIN'
      | 'additionalMetadataURI'
      | 'attributes'
      | 'outSize'
      | 'owner'
      | 'render'
      | 'renderAttributeKey'
      | 'renderRaw'
      | 'supportsInterface',
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: 'RADIUS_MAX',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'RADIUS_MIN',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'additionalMetadataURI',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'attributes',
    values: [BytesLike],
  ): string;
  encodeFunctionData(functionFragment: 'outSize', values?: undefined): string;
  encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
  encodeFunctionData(functionFragment: 'render', values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: 'renderAttributeKey',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'renderRaw',
    values: [BytesLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'supportsInterface',
    values: [BytesLike],
  ): string;

  decodeFunctionResult(functionFragment: 'RADIUS_MAX', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'RADIUS_MIN', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'additionalMetadataURI',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'attributes', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'outSize', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'render', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'renderAttributeKey',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'renderRaw', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'supportsInterface',
    data: BytesLike,
  ): Result;

  events: {};
}

export interface DotMatrixRenderer extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: DotMatrixRendererInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>,
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>,
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    RADIUS_MAX(overrides?: CallOverrides): Promise<[BigNumber]>;

    RADIUS_MIN(overrides?: CallOverrides): Promise<[BigNumber]>;

    additionalMetadataURI(overrides?: CallOverrides): Promise<[string]>;

    attributes(out: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    outSize(overrides?: CallOverrides): Promise<[BigNumber]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    render(out: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    renderAttributeKey(overrides?: CallOverrides): Promise<[string]>;

    renderRaw(out: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides,
    ): Promise<[boolean]>;
  };

  RADIUS_MAX(overrides?: CallOverrides): Promise<BigNumber>;

  RADIUS_MIN(overrides?: CallOverrides): Promise<BigNumber>;

  additionalMetadataURI(overrides?: CallOverrides): Promise<string>;

  attributes(out: BytesLike, overrides?: CallOverrides): Promise<string>;

  outSize(overrides?: CallOverrides): Promise<BigNumber>;

  owner(overrides?: CallOverrides): Promise<string>;

  render(out: BytesLike, overrides?: CallOverrides): Promise<string>;

  renderAttributeKey(overrides?: CallOverrides): Promise<string>;

  renderRaw(out: BytesLike, overrides?: CallOverrides): Promise<string>;

  supportsInterface(
    interfaceId: BytesLike,
    overrides?: CallOverrides,
  ): Promise<boolean>;

  callStatic: {
    RADIUS_MAX(overrides?: CallOverrides): Promise<BigNumber>;

    RADIUS_MIN(overrides?: CallOverrides): Promise<BigNumber>;

    additionalMetadataURI(overrides?: CallOverrides): Promise<string>;

    attributes(out: BytesLike, overrides?: CallOverrides): Promise<string>;

    outSize(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<string>;

    render(out: BytesLike, overrides?: CallOverrides): Promise<string>;

    renderAttributeKey(overrides?: CallOverrides): Promise<string>;

    renderRaw(out: BytesLike, overrides?: CallOverrides): Promise<string>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides,
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    RADIUS_MAX(overrides?: CallOverrides): Promise<BigNumber>;

    RADIUS_MIN(overrides?: CallOverrides): Promise<BigNumber>;

    additionalMetadataURI(overrides?: CallOverrides): Promise<BigNumber>;

    attributes(out: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    outSize(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    render(out: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    renderAttributeKey(overrides?: CallOverrides): Promise<BigNumber>;

    renderRaw(out: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    RADIUS_MAX(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    RADIUS_MIN(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    additionalMetadataURI(
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    attributes(
      out: BytesLike,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    outSize(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    render(
      out: BytesLike,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    renderAttributeKey(
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    renderRaw(
      out: BytesLike,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;
  };
}
