/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DebugRenderer } from './DebugRenderer';
export type { DotMatrixRenderer } from './DotMatrixRenderer';
