"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BrainFuckVM__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var BrainFuckVM__factory_1 = require("./BrainFuckVM__factory");
Object.defineProperty(exports, "BrainFuckVM__factory", { enumerable: true, get: function () { return BrainFuckVM__factory_1.BrainFuckVM__factory; } });
//# sourceMappingURL=index.js.map